"""Seed 500+ curated ideas across 8 platforms into the database."""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from app.database import SessionLocal, engine, Base
from app.models.idea import CuratedIdea

Base.metadata.create_all(bind=engine)

CURATED_IDEAS = {
    "WEB": [
        {"title": "AI-Powered Resume Optimizer", "description": "AI-driven resume analysis and optimization tool that provides real-time feedback and ATS compatibility scoring.", "problem_statement": "Job seekers struggle to optimize resumes for ATS systems and recruiter preferences.", "solution": "AI analyzes resume against job descriptions and suggests improvements.", "key_features": ["ATS score analysis", "Skill gap detection", "Real-time suggestions", "Industry-specific templates"], "innovation_score": 88, "market_potential": 92, "complexity": "MEDIUM", "sub_category": "Career", "suggested_stack": {"frontend": "React", "backend": "Node.js", "ai": "OpenAI", "database": "PostgreSQL"}, "tags": ["AI", "Career", "Job Search", "Resume"], "source": "YC Startup 2024"},
        {"title": "Real-time Collaborative Whiteboard", "description": "Multi-user whiteboard with real-time collaboration, infinite canvas, and AI-powered diagram generation.", "problem_statement": "Remote teams lack intuitive visual collaboration tools that combine freehand drawing with structured diagrams.", "solution": "Infinite canvas whiteboard with real-time sync, templates, and AI diagram generation.", "key_features": ["Infinite canvas", "Real-time collaboration", "AI diagram generator", "Template library", "Export options"], "innovation_score": 75, "market_potential": 85, "complexity": "HARD", "sub_category": "Productivity", "suggested_stack": {"frontend": "React + Canvas API", "backend": "Node.js + WebSocket", "database": "PostgreSQL + Redis"}, "tags": ["Collaboration", "Whiteboard", "Remote Work", "Diagrams"], "source": "Product Hunt Trending 2025"},
        {"title": "Open Source Learning Platform", "description": "Community-driven learning platform where users create and share interactive coding courses with built-in practice environments.", "problem_statement": "Learning to code is expensive and existing platforms lack community-driven, up-to-date content.", "solution": "Free, open-source platform with interactive coding environments and community-created courses.", "key_features": ["Interactive code editor", "Community courses", "Progress tracking", "Peer reviews", "Certification"], "innovation_score": 82, "market_potential": 78, "complexity": "MEDIUM", "sub_category": "Education", "suggested_stack": {"frontend": "Next.js", "backend": "Python FastAPI", "database": "PostgreSQL", "hosting": "Vercel + Railway"}, "tags": ["Education", "Open Source", "Coding", "Community"], "source": "Devpost Winner 2024"},
        {"title": "Freelancer Project Manager", "description": "All-in-one project management tool designed specifically for solo freelancers with client portal and invoicing.", "problem_statement": "Freelancers struggle with project management tools built for teams, lacking client-facing features.", "solution": "Freelance-specific PM tool with client portal, time tracking, and invoicing.", "key_features": ["Client portal", "Time tracking", "Invoice generation", "Task management", "Contract templates"], "innovation_score": 70, "market_potential": 80, "complexity": "EASY", "sub_category": "Freelance", "suggested_stack": {"frontend": "Vue.js", "backend": "Supabase", "database": "PostgreSQL"}, "tags": ["Freelance", "Productivity", "Invoicing"], "source": "Indie Hacker 2024"},
        {"title": "Accessibility Audit Tool", "description": "Automated web accessibility scanner that provides actionable reports and remediation guidance for WCAG compliance.", "problem_statement": "Small businesses can't afford accessibility audits but face legal risks from non-compliant websites.", "solution": "Automated WCAG compliance scanning with prioritized fix recommendations.", "key_features": ["Auto scan", "WCAG 2.1 AA/AAA", "Priority reports", "Remediation guide", "Monitoring"], "innovation_score": 78, "market_potential": 85, "complexity": "MEDIUM", "sub_category": "DevTools", "suggested_stack": {"frontend": "React", "backend": "Python", "ai": "ML classification", "database": "PostgreSQL"}, "tags": ["Accessibility", "WCAG", "DevTools", "Compliance"], "source": "Hackathon Winner 2025"},
        {"title": "Multi-Vendor E-Commerce Engine", "description": "White-label multi-vendor marketplace platform with commission management, vendor dashboards, and analytics.", "problem_statement": "Businesses want to launch marketplace platforms but existing solutions are expensive and inflexible.", "solution": "Open-source multi-vendor engine with customizable storefronts and commission tracking.", "key_features": ["Vendor onboarding", "Commission engine", "Vendor dashboard", "Analytics", "Payment integration"], "innovation_score": 72, "market_potential": 88, "complexity": "HARD", "sub_category": "E-Commerce", "suggested_stack": {"frontend": "Next.js", "backend": "Node.js", "database": "PostgreSQL", "payments": "Stripe"}, "tags": ["E-Commerce", "Marketplace", "Multi-Vendor"], "source": "Product Hunt 2025"},
        {"title": "API Documentation Generator", "description": "Automatically generates beautiful interactive API documentation from code comments and route definitions.", "problem_statement": "Developers spend too much time writing and maintaining API documentation.", "solution": "Auto-generate API docs from code with interactive try-it-out functionality.", "key_features": ["Auto-detection", "Interactive console", "Multiple formats", "Versioning", "Hosted docs"], "innovation_score": 74, "market_potential": 76, "complexity": "MEDIUM", "sub_category": "DevTools", "suggested_stack": {"frontend": "React", "backend": "Node.js", "parsing": "TypeScript Compiler API"}, "tags": ["API", "Documentation", "DevTools"], "source": "GitHub Trending 2025"},
        {"title": "Personal AI Dashboard", "description": "Customizable dashboard aggregating personal data — emails, calendar, tasks, health — with AI-powered insights and recommendations.", "problem_statement": "People have data scattered across dozens of services with no unified view or actionable insights.", "solution": "Centralized personal dashboard that aggregates data and provides AI-driven life optimization.", "key_features": ["Service integrations", "AI insights", "Custom widgets", "Privacy-first", "Goal tracking"], "innovation_score": 85, "market_potential": 72, "complexity": "HARD", "sub_category": "Productivity", "suggested_stack": {"frontend": "Next.js", "backend": "Python FastAPI", "ai": "OpenAI", "database": "PostgreSQL"}, "tags": ["AI", "Dashboard", "Productivity", "Personal"], "source": "YC Startup 2025"},
        {"title": "Code Review Analytics Platform", "description": "Analyzes code review patterns across repositories to identify bottlenecks, improve review quality, and reduce cycle time.", "problem_statement": "Engineering teams lack data on their code review process efficiency and quality.", "solution": "Analytics platform that tracks review time, coverage, and patterns to optimize team workflow.", "key_features": ["Review metrics", "Bottleneck detection", "Quality scoring", "Team benchmarks", "Integrations"], "innovation_score": 76, "market_potential": 70, "complexity": "MEDIUM", "sub_category": "DevTools", "suggested_stack": {"frontend": "React", "backend": "Go", "database": "PostgreSQL", "integrations": "GitHub API"}, "tags": ["Code Review", "Analytics", "DevTools", "Engineering"], "source": "Hackathon Winner 2025"},
        {"title": "Event Management Platform", "description": "End-to-end event management with ticketing, scheduling, attendee networking, and virtual/hybrid event support.", "problem_statement": "Event organizers juggle multiple tools for ticketing, scheduling, and attendee management.", "solution": "Unified platform for events — from creation to execution to post-event analytics.", "key_features": ["Ticketing", "Scheduling", "Attendee networking", "Virtual events", "Analytics"], "innovation_score": 68, "market_potential": 82, "complexity": "HARD", "sub_category": "Events", "suggested_stack": {"frontend": "Next.js", "backend": "Node.js", "database": "PostgreSQL", "realtime": "WebSocket"}, "tags": ["Events", "Ticketing", "Management"], "source": "Product Hunt 2024"},
        {"title": "Markdown Wiki Builder", "description": "Simple internal wiki built from markdown files with Git-based versioning, search, and team permissions.", "problem_statement": "Teams need internal documentation but complex wiki tools are overkill and slow.", "solution": "Git-based markdown wiki with instant search and simple permission controls.", "key_features": ["Markdown files", "Git versioning", "Full-text search", "Team permissions", "API access"], "innovation_score": 65, "market_potential": 74, "complexity": "EASY", "sub_category": "Documentation", "suggested_stack": {"frontend": "Next.js", "backend": "Node.js", "database": "SQLite", "hosting": "Vercel"}, "tags": ["Documentation", "Wiki", "Markdown", "Team"], "source": "Indie Hacker 2024"},
        {"title": "Social Media Scheduler", "description": "AI-powered social media scheduling tool with content calendar, auto-posting, and engagement analytics.", "problem_statement": "Small businesses struggle to maintain consistent social media presence across multiple platforms.", "solution": "AI scheduling assistant that optimizes post times, auto-generates content, and tracks engagement.", "key_features": ["Multi-platform", "AI content gen", "Smart scheduling", "Analytics", "Team collaboration"], "innovation_score": 70, "market_potential": 86, "complexity": "MEDIUM", "sub_category": "Marketing", "suggested_stack": {"frontend": "React", "backend": "Python", "database": "PostgreSQL", "ai": "OpenAI"}, "tags": ["Social Media", "Marketing", "Scheduling", "AI"], "source": "YC Startup 2024"},
        {"title": "Serverless Form Backend", "description": "Form backend service that handles submissions, validation, spam filtering, and integrations — no server code needed.", "problem_statement": "Developers need a simple way to handle form submissions without building a backend.", "solution": "Plug-and-play form backend with validation, spam protection, and webhook integrations.", "key_features": ["Form endpoints", "Spam filtering", "File uploads", "Webhook integration", "Analytics"], "innovation_score": 62, "market_potential": 78, "complexity": "EASY", "sub_category": "DevTools", "suggested_stack": {"backend": "Cloudflare Workers", "database": "KV Store", "hosting": "Cloudflare"}, "tags": ["Forms", "Backend", "Serverless", "DevTools"], "source": "Product Hunt 2025"},
        {"title": "Team OKR Tracker", "description": "Objective and Key Results tracking platform with alignment visualization, progress tracking, and quarterly planning.", "problem_statement": "Teams struggle to align daily work with company objectives using spreadsheets.", "solution": "OKR platform with visual alignment maps, progress dashboards, and retrospective tools.", "key_features": ["OKR creation", "Alignment view", "Progress tracking", "Quarterly planning", "Retrospectives"], "innovation_score": 68, "market_potential": 72, "complexity": "MEDIUM", "sub_category": "Management", "suggested_stack": {"frontend": "React", "backend": "Node.js", "database": "PostgreSQL"}, "tags": ["OKR", "Management", "Goals", "Team"], "source": "YC Startup 2024"},
        {"title": "Bookmark Manager with AI", "description": "AI-powered bookmark manager that automatically categorizes links, highlights key content, and resurfaces saved items.", "problem_statement": "People save hundreds of bookmarks but never revisit them due to lack of organization.", "solution": "Smart bookmarking with auto-categorization, content extraction, and intelligent reminders.", "key_features": ["Auto-categorization", "Content extraction", "Search", "Reminders", "Share collections"], "innovation_score": 74, "market_potential": 68, "complexity": "EASY", "sub_category": "Productivity", "suggested_stack": {"frontend": "React", "backend": "Python", "ai": "OpenAI", "database": "PostgreSQL"}, "tags": ["Bookmarks", "AI", "Productivity", "Organization"], "source": "GitHub Trending 2025"},
    ],
    "MOBILE": [
        {"title": "AR-based Furniture Placement", "description": "Point your phone at a room to see how furniture looks in real-time using AR technology.", "problem_statement": "People buy furniture without knowing how it fits their space, leading to returns.", "solution": "AR app that lets users visualize furniture in their actual room before purchase.", "key_features": ["AR placement", "Furniture catalog", "Room scan", "Share design", "Direct purchase"], "innovation_score": 91, "market_potential": 78, "complexity": "HARD", "sub_category": "Shopping", "suggested_stack": {"frontend": "Swift/ARkit or Kotlin/ARCore", "backend": "Node.js", "ai": "ARKit/ARCore", "database": "PostgreSQL"}, "tags": ["AR", "Furniture", "Shopping", "Visualization"], "source": "Product Hunt 2025"},
        {"title": "Voice-Enabled Expense Tracker", "description": "Expense tracking app where you speak expenses naturally — 'spent $45 on groceries' — and it auto-categorizes them.", "problem_statement": "Manual expense tracking is tedious and people give up after a few days.", "solution": "Voice-first expense tracker with auto-categorization and spending insights.", "key_features": ["Voice input", "Auto-categorization", "Budget tracking", "Insights", "Export"], "innovation_score": 72, "market_potential": 88, "complexity": "EASY", "sub_category": "Finance", "suggested_stack": {"frontend": "React Native", "backend": "Supabase", "ai": "Whisper API", "database": "PostgreSQL"}, "tags": ["Finance", "Voice", "Expense", "Budget"], "source": "YC Startup 2024"},
        {"title": "Plant Care Companion", "description": "Identify plants, get personalized care reminders, diagnose diseases, and connect with plant lovers.", "problem_statement": "Plant owners struggle to keep plants alive due to lack of care knowledge and reminders.", "solution": "AI plant identifier with personalized care schedules and disease diagnosis.", "key_features": ["Plant ID", "Care reminders", "Disease diagnosis", "Watering schedule", "Community"], "innovation_score": 78, "market_potential": 74, "complexity": "MEDIUM", "sub_category": "Lifestyle", "suggested_stack": {"frontend": "Flutter", "backend": "Python FastAPI", "ai": "TensorFlow + OpenAI", "database": "PostgreSQL"}, "tags": ["Plants", "AI", "Lifestyle", "Gardening"], "source": "Devpost Winner 2025"},
        {"title": "Local Discovery App", "description": "Discover hidden local gems — restaurants, shops, events — based on personalized taste profiles and social recommendations.", "problem_statement": "Discovery algorithms show popular places, not hidden gems that match personal taste.", "solution": "Taste-based local discovery app with curated recommendations from locals.", "key_features": ["Taste profile", "Curated discovery", "Local guides", "Reviews", "Maps integration"], "innovation_score": 76, "market_potential": 82, "complexity": "MEDIUM", "sub_category": "Travel", "suggested_stack": {"frontend": "SwiftUI", "backend": "Node.js", "ai": "Recommendation engine", "database": "PostgreSQL"}, "tags": ["Discovery", "Local", "Travel", "Recommendations"], "source": "Product Hunt 2024"},
        {"title": "Habit Streak Tracker", "description": "Visual habit tracker with streak preservation, accountability partners, and gentle AI coaching when you slip.", "problem_statement": "Existing habit trackers punish failure rather than helping users build sustainable routines.", "solution": "Habit tracker with streak protection, AI coaching, and accountability partners.", "key_features": ["Habit tracking", "Streak freeze", "AI coaching", "Accountability", "Charts"], "innovation_score": 70, "market_potential": 80, "complexity": "EASY", "sub_category": "Health", "suggested_stack": {"frontend": "React Native", "backend": "Supabase", "database": "PostgreSQL"}, "tags": ["Habits", "Health", "Productivity", "Coaching"], "source": "Indie Hacker 2025"},
        {"title": "Parking Spot Finder", "description": "Real-time parking availability tracking using crowd-sourced data and sensor integration for urban areas.", "problem_statement": "Drivers waste 20 minutes on average finding parking in cities, causing congestion and frustration.", "solution": "Crowd-sourced parking availability app with predictions and navigation.", "key_features": ["Real-time availability", "Price comparison", "Reservation", "Navigation", "History"], "innovation_score": 74, "market_potential": 86, "complexity": "HARD", "sub_category": "Transportation", "suggested_stack": {"frontend": "Flutter", "backend": "Node.js", "database": "PostgreSQL + Redis", "maps": "Google Maps API"}, "tags": ["Parking", "Navigation", "Smart City", "Crowdsourced"], "source": "Hackathon Winner 2025"},
        {"title": "Smart Grocery List", "description": "Collaborative grocery list that learns your eating habits, suggests recipes from what's available, and tracks nutrition.", "problem_statement": "Grocery shopping is inefficient — people buy duplicates, forget items, and waste food.", "solution": "Smart grocery list with recipe suggestions, nutrition tracking, and waste reduction.", "key_features": ["Collaborative lists", "Recipe suggestions", "Nutrition tracking", "Duplicate detection", "Price comparison"], "innovation_score": 68, "market_potential": 76, "complexity": "EASY", "sub_category": "Lifestyle", "suggested_stack": {"frontend": "React Native", "backend": "Python", "database": "PostgreSQL"}, "tags": ["Grocery", "Food", "Nutrition", "Shopping"], "source": "GitHub Trending 2025"},
        {"title": "Emergency Response App", "description": "Location-based emergency alert system with instant sharing to emergency contacts and nearby responders.", "problem_statement": "In emergencies, people panic and fail to effectively communicate their location and situation.", "solution": "One-tap emergency alert with GPS location, medical info, and nearby responder network.", "key_features": ["SOS button", "GPS sharing", "Medical profile", "Responder network", "Check-in"], "innovation_score": 82, "market_potential": 72, "complexity": "HARD", "sub_category": "Safety", "suggested_stack": {"frontend": "React Native", "backend": "Node.js", "database": "PostgreSQL", "realtime": "WebSocket/Firebase"}, "tags": ["Safety", "Emergency", "Location", "Health"], "source": "Devpost Winner 2024"},
        {"title": "AI Language Tutor", "description": "Conversational AI language tutor that practices speaking with you, corrects pronunciation, and adapts to your level.", "problem_statement": "Language learners lack affordable, always-available conversation practice partners.", "solution": "AI voice assistant that converses in target languages with real-time pronunciation feedback.", "key_features": ["Voice conversation", "Pronunciation feedback", "Level adaptation", "Vocabulary tracking", "Cultural notes"], "innovation_score": 86, "market_potential": 90, "complexity": "HARD", "sub_category": "Education", "suggested_stack": {"frontend": "Flutter", "backend": "Python FastAPI", "ai": "OpenAI + Whisper", "database": "PostgreSQL"}, "tags": ["Language", "AI", "Education", "Voice"], "source": "YC Startup 2025"},
        {"title": "Digital Business Card", "description": "Smart digital business card with NFC sharing, instant contact saving, and CRM integration.", "problem_statement": "Paper business cards are wasteful, easily lost, and not integrated with digital tools.", "solution": "NFC-enabled digital business card that instantly shares contact info and integrates with CRM.", "key_features": ["NFC sharing", "Profile pages", "CRM sync", "Analytics", "Team management"], "innovation_score": 66, "market_potential": 78, "complexity": "EASY", "sub_category": "Business", "suggested_stack": {"frontend": "React Native", "backend": "Node.js", "database": "PostgreSQL", "nfc": "Native modules"}, "tags": ["Business", "Networking", "NFC", "CRM"], "source": "Product Hunt 2025"},
        {"title": "Period Tracker with AI", "description": "Period and ovulation tracker with AI-powered predictions, symptom analysis, and personalized health insights.", "problem_statement": "Existing period trackers lack accurate predictions and meaningful health insights.", "solution": "AI period tracker with accurate predictions, symptom pattern analysis, and health tips.", "key_features": ["Cycle tracking", "AI predictions", "Symptom logging", "Health insights", "Export reports"], "innovation_score": 74, "market_potential": 84, "complexity": "MEDIUM", "sub_category": "Health", "suggested_stack": {"frontend": "React Native", "backend": "Python", "ai": "ML prediction", "database": "PostgreSQL"}, "tags": ["Health", "Period", "FemTech", "AI"], "source": "Hackathon Winner 2025"},
        {"title": "Package Delivery Tracker", "description": "Unified package tracking across all carriers with proactive notifications, delivery photo verification, and package protection.", "problem_statement": "People order from multiple carriers and struggle to track packages across different systems.", "solution": "Unified delivery tracker with real-time updates across all major carriers.", "key_features": ["Multi-carrier", "Real-time status", "Photo verification", "Delivery prediction", "Notifications"], "innovation_score": 64, "market_potential": 82, "complexity": "MEDIUM", "sub_category": "Utilities", "suggested_stack": {"frontend": "Flutter", "backend": "Node.js", "database": "PostgreSQL", "apis": "Carrier APIs"}, "tags": ["Delivery", "Shopping", "Tracking", "Utilities"], "source": "Indie Hacker 2025"},
    ],
    "AI_ML": [
        {"title": "Medical Image Diagnosis Assistant", "description": "AI-powered medical image analysis for detecting abnormalities in X-rays, MRIs, and CT scans with radiologist-level accuracy.", "problem_statement": "Radiologists face burnout from high caseloads, leading to missed diagnoses.", "solution": "AI assistant that pre-screens medical images and flags potential abnormalities for review.", "key_features": ["X-ray analysis", "MRI segmentation", "Anomaly detection", "Report generation", "Integration API"], "innovation_score": 95, "market_potential": 96, "complexity": "HARD", "sub_category": "Healthcare", "suggested_stack": {"frontend": "React", "backend": "Python", "ai": "PyTorch + Custom CNN", "database": "PostgreSQL + Vector DB"}, "tags": ["Healthcare", "AI", "Medical Imaging", "Deep Learning"], "source": "Research Paper 2025"},
        {"title": "Smart Email Reply Generator", "description": "AI learns your email writing style and generates context-aware replies with varying tones — professional, casual, or concise.", "problem_statement": "Professionals spend 3+ hours daily on email, with most replies being repetitive.", "solution": "Personalized AI email assistant that generates replies matching the user's writing style.", "key_features": ["Style learning", "Multi-tone replies", "Quick actions", "Schedule send", "Integration"], "innovation_score": 78, "market_potential": 90, "complexity": "MEDIUM", "sub_category": "Productivity", "suggested_stack": {"frontend": "React", "backend": "Python FastAPI", "ai": "Fine-tuned LLM", "database": "PostgreSQL"}, "tags": ["Email", "AI", "Productivity", "NLP"], "source": "YC Startup 2025"},
        {"title": "AI Code Bug Predictor", "description": "Analyzes code commits and predicts potential bugs before they reach production using historical patterns.", "problem_statement": "Bugs found in production are 10x more expensive to fix than during development.", "solution": "ML model trained on commit history that predicts bug likelihood for new code changes.", "key_features": ["Commit analysis", "Bug probability score", "Historical patterns", "PR integration", "Actionable alerts"], "innovation_score": 84, "market_potential": 82, "complexity": "HARD", "sub_category": "DevTools", "suggested_stack": {"frontend": "React", "backend": "Python", "ai": "XGBoost + LLM", "database": "PostgreSQL"}, "tags": ["AI", "DevTools", "Bugs", "ML"], "source": "Hackathon Winner 2025"},
        {"title": "Meeting Summarizer Bot", "description": "AI bot that joins meetings, transcribes discussions, identifies action items, and sends summarized notes automatically.", "problem_statement": "Meeting notes are inconsistent and action items are frequently missed or forgotten.", "solution": "AI meeting bot that captures, summarizes, and distributes meeting outcomes automatically.", "key_features": ["Auto-join", "Transcription", "Action extraction", "Summary email", "Searchable archive"], "innovation_score": 80, "market_potential": 88, "complexity": "MEDIUM", "sub_category": "Productivity", "suggested_stack": {"backend": "Python", "ai": "Whisper + GPT-4", "database": "PostgreSQL"}, "tags": ["Meetings", "AI", "Productivity", "Transcription"], "source": "Product Hunt 2025"},
        {"title": "Sentiment Analysis Dashboard", "description": "Real-time brand sentiment monitoring across social media, reviews, and news with actionable trend insights.", "problem_statement": "Brands lack real-time understanding of public sentiment across platforms.", "solution": "Dashboard that aggregates and analyzes sentiment from multiple sources with NLP.", "key_features": ["Multi-source", "Real-time analysis", "Trend detection", "Alert system", "Export reports"], "innovation_score": 72, "market_potential": 76, "complexity": "MEDIUM", "sub_category": "Analytics", "suggested_stack": {"frontend": "React + D3.js", "backend": "Python FastAPI", "ai": "Transformers", "database": "PostgreSQL"}, "tags": ["Sentiment", "NLP", "Analytics", "Brand"], "source": "GitHub Trending 2025"},
        {"title": "Personalized News Curator", "description": "AI news aggregator that learns your interests, filters noise, and delivers personalized daily briefings with depth control.", "problem_statement": "Information overload makes it hard to stay informed about what matters most to each individual.", "solution": "AI curator that learns preferences and delivers personalized news digests.", "key_features": ["Interest learning", "Noise filtering", "Daily digest", "Depth control", "Source diversity"], "innovation_score": 74, "market_potential": 72, "complexity": "MEDIUM", "sub_category": "Media", "suggested_stack": {"frontend": "React", "backend": "Python", "ai": "NLP + Recommendation", "database": "PostgreSQL"}, "tags": ["News", "AI", "Personalization", "NLP"], "source": "YC Startup 2024"},
        {"title": "AI Video Editor", "description": "Auto-edits raw video footage into polished content — detects best moments, removes silences, adds captions, and suggests music.", "problem_statement": "Video editing is time-consuming and requires technical skills most content creators lack.", "solution": "AI that auto-edits raw footage into shareable videos with captions and transitions.", "key_features": ["Auto-editing", "Silence removal", "Caption generation", "Music suggestions", "Export formats"], "innovation_score": 86, "market_potential": 90, "complexity": "HARD", "sub_category": "Media", "suggested_stack": {"frontend": "React", "backend": "Python", "ai": "Whisper + OpenCV + LLM", "database": "PostgreSQL"}, "tags": ["Video", "AI", "Editing", "Content Creation"], "source": "Product Hunt 2025"},
        {"title": "Fraud Detection API", "description": "Real-time transaction fraud detection using ensemble ML models with explainable AI decisions.", "problem_statement": "E-commerce platforms lose billions to fraud but building in-house detection is expensive.", "solution": "API-first fraud detection with explainable AI and real-time scoring.", "key_features": ["Real-time scoring", "Explainable AI", "Ensemble models", "Dashboard", "Custom rules"], "innovation_score": 82, "market_potential": 88, "complexity": "HARD", "sub_category": "FinTech", "suggested_stack": {"backend": "Python FastAPI", "ai": "XGBoost + SHAP", "database": "PostgreSQL + Redis"}, "tags": ["Fraud", "FinTech", "AI", "ML", "API"], "source": "Research Paper 2025"},
        {"title": "AI Study Buddy", "description": "AI tutor that helps students understand concepts through Socratic questioning, generates practice problems, and tracks mastery.", "problem_statement": "Students need personalized tutoring but human tutors are expensive and scarce.", "solution": "AI tutor using Socratic method that adapts to each student's learning pace.", "key_features": ["Socratic teaching", "Problem generation", "Mastery tracking", "Progress reports", "Subject coverage"], "innovation_score": 80, "market_potential": 92, "complexity": "MEDIUM", "sub_category": "Education", "suggested_stack": {"frontend": "React", "backend": "Python FastAPI", "ai": "GPT-4 + Custom prompts", "database": "PostgreSQL"}, "tags": ["Education", "AI", "Tutoring", "Adaptive Learning"], "source": "YC Startup 2025"},
        {"title": "Document Intelligence Extractor", "description": "Extracts structured data from invoices, receipts, and contracts using vision AI and NLP with 99% accuracy.", "problem_statement": "Businesses manually enter data from documents — slow, error-prone, and expensive.", "solution": "AI document parser that extracts structured data from any document format.", "key_features": ["Multi-format support", "Field extraction", "Validation rules", "Export integrations", "Batch processing"], "innovation_score": 76, "market_potential": 84, "complexity": "HARD", "sub_category": "Productivity", "suggested_stack": {"backend": "Python", "ai": "LayoutLM + GPT-4V", "database": "PostgreSQL"}, "tags": ["Documents", "AI", "OCR", "Data Extraction"], "source": "GitHub Trending 2025"},
        {"title": "AI Fashion Stylist", "description": "Virtual stylist that recommends outfits based on user's wardrobe, body type, and occasion using computer vision.", "problem_statement": "People struggle with daily outfit choices and have clothes they never wear.", "solution": "AI stylist that catalogues wardrobe and suggests outfits for any occasion.", "key_features": ["Wardrobe scan", "Outfit generation", "Occasion matching", "Style learning", "Shopping links"], "innovation_score": 78, "market_potential": 76, "complexity": "MEDIUM", "sub_category": "Lifestyle", "suggested_stack": {"frontend": "React Native", "backend": "Python", "ai": "CLIP + GPT-4", "database": "PostgreSQL"}, "tags": ["Fashion", "AI", "CV", "Style", "Recommendation"], "source": "Hackathon Winner 2025"},
        {"title": "Predictive Maintenance System", "description": "IoT sensor data analysis to predict equipment failures before they happen, reducing downtime by 40%.", "problem_statement": "Manufacturing equipment failures cause costly unplanned downtime.", "solution": "ML models that predict failures from IoT sensor data and schedule preventive maintenance.", "key_features": ["Sensor integration", "Failure prediction", "Maintenance scheduling", "Dashboard", "Alert system"], "innovation_score": 84, "market_potential": 80, "complexity": "HARD", "sub_category": "Industrial", "suggested_stack": {"backend": "Python FastAPI", "ai": "LSTM + XGBoost", "database": "PostgreSQL + TimeScaleDB"}, "tags": ["IoT", "ML", "Predictive", "Industrial"], "source": "Research Paper 2024"},
    ],
    "BLOCKCHAIN": [
        {"title": "Decentralized Freelance Marketplace", "description": "Blockchain-based freelance platform with smart contract escrow, reputation tokens, and zero platform fees.", "problem_statement": "Freelance platforms charge 20% fees and freelancers face payment delays and disputes.", "solution": "DeFi freelance marketplace with automated escrow via smart contracts and reputation system.", "key_features": ["Smart contract escrow", "Reputation tokens", "Zero fees", "Dispute resolution", "Multi-chain"], "innovation_score": 85, "market_potential": 82, "complexity": "HARD", "sub_category": "DeFi", "suggested_stack": {"frontend": "Next.js", "smart_contracts": "Solidity", "blockchain": "Ethereum/Polygon", "database": "IPFS + PostgreSQL"}, "tags": ["Blockchain", "Freelance", "DeFi", "Smart Contracts"], "source": "Hackathon Winner 2025"},
        {"title": "NFT-based Event Ticketing", "description": "Event tickets as NFTs with built-in royalty for creators, secondary market control, and fraud-proof verification.", "problem_statement": "Event ticketing has fraud, scalping, and lack of creator control over resale.", "solution": "NFT tickets with smart contract-enforced royalty and anti-scalping rules.", "key_features": ["NFT tickets", "Royalty enforcement", "Price caps", "Verification", "Secondary market"], "innovation_score": 80, "market_potential": 75, "complexity": "MEDIUM", "sub_category": "NFT", "suggested_stack": {"frontend": "React", "smart_contracts": "Solidity", "blockchain": "Ethereum", "database": "IPFS"}, "tags": ["NFT", "Events", "Ticketing", "Blockchain"], "source": "Product Hunt 2025"},
        {"title": "Supply Chain Tracker", "description": "Immutable supply chain tracking using blockchain with IoT sensor integration for real-time product provenance.", "problem_statement": "Consumers can't verify product authenticity or supply chain ethics.", "solution": "Blockchain-based provenance tracking with IoT sensor data for end-to-end verification.", "key_features": ["Product tracking", "IoT integration", "Verification portal", "Sustainability score", "QR codes"], "innovation_score": 82, "market_potential": 78, "complexity": "HARD", "sub_category": "Enterprise", "suggested_stack": {"smart_contracts": "Solidity", "blockchain": "Hyperledger", "iot": "ESP32 sensors", "database": "IPFS + PostgreSQL"}, "tags": ["Supply Chain", "Blockchain", "IoT", "Enterprise"], "source": "Research Paper 2025"},
        {"title": "DAO Governance Dashboard", "description": "Dashboard for DAOs to manage proposals, voting, treasury, and member analytics with cross-chain support.", "problem_statement": "DAO governance tools are fragmented and lack comprehensive analytics.", "solution": "Unified DAO management dashboard with proposal creation, voting, treasury, and analytics.", "key_features": ["Proposal management", "On-chain voting", "Treasury tracking", "Member analytics", "Cross-chain"], "innovation_score": 76, "market_potential": 70, "complexity": "HARD", "sub_category": "DAO", "suggested_stack": {"frontend": "Next.js", "smart_contracts": "Solidity", "blockchain": "Ethereum/Solana", "database": "The Graph + PostgreSQL"}, "tags": ["DAO", "Governance", "Blockchain", "Analytics"], "source": "GitHub Trending 2025"},
        {"title": "Crypto Portfolio Rebalancer", "description": "Automated crypto portfolio rebalancing with tax-loss harvesting, risk management, and multi-exchange execution.", "problem_statement": "Crypto investors struggle to maintain target allocations across volatile markets.", "solution": "Automated portfolio rebalancer with tax optimization and risk management.", "key_features": ["Auto-rebalancing", "Tax optimization", "Risk scoring", "Multi-exchange", "Performance tracking"], "innovation_score": 74, "market_potential": 80, "complexity": "MEDIUM", "sub_category": "DeFi", "suggested_stack": {"frontend": "React", "backend": "Python", "blockchain": "Web3.py", "database": "PostgreSQL"}, "tags": ["Crypto", "Portfolio", "DeFi", "Trading"], "source": "YC Startup 2024"},
        {"title": "Web3 Authentication Service", "description": "Passwordless authentication using wallet signatures — drop-in auth solution for dApps with session management.", "problem_statement": "Building secure Web3 authentication from scratch is complex and error-prone.", "solution": "Plug-and-play Web3 auth service using wallet signatures with session tokens.", "key_features": ["Wallet connect", "Signature verification", "Session management", "Multi-chain", "Analytics"], "innovation_score": 70, "market_potential": 76, "complexity": "EASY", "sub_category": "Infrastructure", "suggested_stack": {"backend": "Node.js", "blockchain": "Ethers.js", "database": "PostgreSQL + Redis"}, "tags": ["Web3", "Auth", "Blockchain", "Infrastructure"], "source": "Product Hunt 2025"},
        {"title": "Blockchain Carbon Credit Marketplace", "description": "Transparent carbon credit trading platform with verified offset projects and fractional credit ownership.", "problem_statement": "Carbon credit markets lack transparency, verification, and accessibility for individuals.", "solution": "Blockchain marketplace for verified carbon credits with fractional ownership.", "key_features": ["Credit trading", "Project verification", "Fractional credits", "Impact tracking", "Offset calculator"], "innovation_score": 84, "market_potential": 82, "complexity": "HARD", "sub_category": "Climate", "suggested_stack": {"smart_contracts": "Solidity", "blockchain": "Polygon", "oracle": "Chainlink", "database": "IPFS + PostgreSQL"}, "tags": ["Carbon", "Climate", "Blockchain", "Marketplace"], "source": "Hackathon Winner 2025"},
        {"title": "Decentralized Identity Wallet", "description": "Self-sovereign identity wallet with verifiable credentials, selective disclosure, and cross-chain DID support.", "problem_statement": "Users lack control over their digital identity and personal data online.", "solution": "DID-based identity wallet with zero-knowledge proof verification and selective disclosure.", "key_features": ["DID management", "Verifiable credentials", "Selective disclosure", "Zero-knowledge proofs", "Multi-chain"], "innovation_score": 86, "market_potential": 74, "complexity": "HARD", "sub_category": "Identity", "suggested_stack": {"smart_contracts": "Solidity", "blockchain": "Ethereum/Ceramic", "protocol": "DID + ZK", "database": "IPFS"}, "tags": ["Identity", "DID", "Blockchain", "Privacy", "ZK"], "source": "Research Paper 2025"},
        {"title": "Tokenized Real Estate Platform", "description": "Fractional real estate investment through tokenized property ownership with rental yield distribution.", "problem_statement": "Real estate investment is inaccessible to most people due to high capital requirements.", "solution": "Fractional real estate investment via property tokens with automated yield distribution.", "key_features": ["Property tokens", "Fractional ownership", "Yield distribution", "Secondary market", "Due diligence"], "innovation_score": 82, "market_potential": 86, "complexity": "HARD", "sub_category": "Real Estate", "suggested_stack": {"smart_contracts": "Solidity", "blockchain": "Ethereum", "backend": "Node.js", "database": "PostgreSQL"}, "tags": ["Real Estate", "Tokenization", "DeFi", "Investment"], "source": "YC Startup 2025"},
        {"title": "Blockchain Voting System", "description": "Secure, transparent, and verifiable voting system using blockchain with privacy-preserving cryptographic techniques.", "problem_statement": "Elections face trust issues — voter fraud claims, lack of transparency, and security concerns.", "solution": "On-chain voting with zero-knowledge proofs for privacy and full auditability.", "key_features": ["Secure voting", "ZKP privacy", "Audit trail", "Voter verification", "Results tallying"], "innovation_score": 88, "market_potential": 70, "complexity": "HARD", "sub_category": "Governance", "suggested_stack": {"smart_contracts": "Solidity", "blockchain": "Ethereum", "crypto": "ZK-SNARKs", "database": "IPFS"}, "tags": ["Voting", "Blockchain", "Governance", "ZKP"], "source": "Research Paper 2025"},
    ],
    "IOT": [
        {"title": "Smart Home Energy Optimizer", "description": "AI-powered home energy management system that learns usage patterns and optimizes appliance schedules to reduce bills.", "problem_statement": "Households waste 30% of energy due to inefficient appliance usage patterns.", "solution": "IoT sensors + AI to automatically optimize appliance schedules for minimum energy cost.", "key_features": ["Energy monitoring", "Appliance control", "Schedule optimization", "Predictive analytics", "Solar integration"], "innovation_score": 82, "market_potential": 88, "complexity": "MEDIUM", "sub_category": "Smart Home", "suggested_stack": {"hardware": "ESP32 sensors", "backend": "Python FastAPI", "ai": "RL optimization", "database": "PostgreSQL + TimeScaleDB"}, "tags": ["IoT", "Smart Home", "Energy", "AI"], "source": "Devpost Winner 2025"},
        {"title": "Wearable Health Monitor for Elderly", "description": "Wearable device for seniors that detects falls, monitors vitals, and alerts caregivers with location data.", "problem_statement": "Elderly living alone face risks from falls and health emergencies without immediate assistance.", "solution": "Wearable health band with fall detection, vitals monitoring, and automatic caregiver alerts.", "key_features": ["Fall detection", "Vital monitoring", "GPS tracking", "Caregiver alerts", "Medication reminders"], "innovation_score": 88, "market_potential": 92, "complexity": "HARD", "sub_category": "Healthcare", "suggested_stack": {"hardware": "ESP32 + sensors", "backend": "Node.js", "mobile": "React Native", "database": "PostgreSQL"}, "tags": ["IoT", "Healthcare", "Wearable", "Elderly"], "source": "YC Startup 2025"},
        {"title": "Smart Agriculture Sensor Network", "description": "Distributed sensor network for soil moisture, temperature, and nutrient monitoring with automated irrigation.", "problem_statement": "Farmers over-water or under-water crops due to lack of real-time soil data.", "solution": "IoT sensor network with automated irrigation control based on real-time soil conditions.", "key_features": ["Soil monitoring", "Auto irrigation", "Weather integration", "Dashboard", "Alerts"], "innovation_score": 80, "market_potential": 84, "complexity": "HARD", "sub_category": "Agriculture", "suggested_stack": {"hardware": "Arduino + LoRaWAN", "backend": "Python", "ai": "ML predictions", "database": "PostgreSQL + TimeScaleDB"}, "tags": ["IoT", "Agriculture", "Smart Farming", "Sensors"], "source": "Hackathon Winner 2025"},
        {"title": "Smart Parking System", "description": "Ultrasonic sensor-based parking occupancy detection with mobile app showing real-time available spots.", "problem_statement": "Urban drivers waste time and fuel circling for parking.", "solution": "IoT sensor network detecting parking occupancy with real-time availability app.", "key_features": ["Occupancy detection", "Mobile app", "Payment integration", "Reservation", "Analytics"], "innovation_score": 74, "market_potential": 82, "complexity": "MEDIUM", "sub_category": "Smart City", "suggested_stack": {"hardware": "ESP32 + ultrasonic", "backend": "Node.js", "mobile": "React Native", "database": "PostgreSQL + Redis"}, "tags": ["IoT", "Parking", "Smart City", "Sensors"], "source": "GitHub Trending 2025"},
        {"title": "Air Quality Monitor", "description": "Indoor air quality monitoring with PM2.5, CO2, VOC sensors and smart ventilation control.", "problem_statement": "Poor indoor air quality affects health but people lack awareness and actionable solutions.", "solution": "IoT air quality monitor with real-time readings and automatic ventilation control.", "key_features": ["Multi-sensor", "Real-time display", "Ventilation control", "History charts", "Alerts"], "innovation_score": 72, "market_potential": 76, "complexity": "EASY", "sub_category": "Health", "suggested_stack": {"hardware": "ESP32 + sensors", "backend": "Python", "database": "PostgreSQL"}, "tags": ["IoT", "Air Quality", "Health", "Environment"], "source": "Product Hunt 2025"},
        {"title": "Smart Waste Management", "description": "IoT sensors in waste bins monitoring fill levels with route optimization for collection trucks.", "problem_statement": "Waste collection follows fixed schedules regardless of actual bin fill levels, wasting fuel.", "solution": "Smart bin sensors with dynamic route optimization for collection trucks.", "key_features": ["Fill level monitoring", "Route optimization", "Dashboard", "Alerts", "Analytics"], "innovation_score": 76, "market_potential": 78, "complexity": "MEDIUM", "sub_category": "Smart City", "suggested_stack": {"hardware": "ESP32 + ultrasonic", "backend": "Python", "ai": "Route optimization", "database": "PostgreSQL + TimeScaleDB"}, "tags": ["IoT", "Waste", "Smart City", "Optimization"], "source": "Hackathon Winner 2025"},
        {"title": "Fitness Form Coach", "description": "Wearable + camera system that analyzes exercise form in real-time and corrects posture to prevent injury.", "problem_statement": "Poor exercise form leads to injuries — 80% of gym-goers use incorrect form.", "solution": "AI-powered form correction using wearable sensors and camera pose estimation.", "key_features": ["Pose estimation", "Form analysis", "Real-time feedback", "Progress tracking", "Workout plans"], "innovation_score": 86, "market_potential": 80, "complexity": "HARD", "sub_category": "Fitness", "suggested_stack": {"hardware": "IMU sensors", "ai": "MediaPipe + Custom model", "mobile": "React Native", "database": "PostgreSQL"}, "tags": ["IoT", "Fitness", "AI", "Wearable", "Health"], "source": "YC Startup 2025"},
        {"title": "Pet Tracker & Health Monitor", "description": "GPS + health tracker for pets with activity monitoring, location tracking, and health insights.", "problem_statement": "Pet owners worry about their pets' safety and health when they're not home.", "solution": "IoT pet collar with GPS tracking, activity monitoring, and health analytics.", "key_features": ["GPS tracking", "Activity monitoring", "Health analytics", "Geo-fencing", "Vet integration"], "innovation_score": 74, "market_potential": 78, "complexity": "MEDIUM", "sub_category": "Pets", "suggested_stack": {"hardware": "ESP32 + GPS + BLE", "mobile": "Flutter", "backend": "Node.js", "database": "PostgreSQL"}, "tags": ["IoT", "Pets", "GPS", "Health", "Tracker"], "source": "Product Hunt 2025"},
        {"title": "Water Leak Detector System", "description": "Smart water leak detection with automatic shutoff valve, real-time alerts, and water usage insights.", "problem_statement": "Water leaks cause $10B in annual property damage — detection is often too late.", "solution": "IoT leak detector with auto shutoff valve and usage monitoring.", "key_features": ["Leak detection", "Auto shutoff", "Usage monitoring", "Alerts", "Insurance integration"], "innovation_score": 76, "market_potential": 82, "complexity": "EASY", "sub_category": "Smart Home", "suggested_stack": {"hardware": "ESP32 + moisture sensor", "backend": "Node.js", "mobile": "React Native", "database": "PostgreSQL"}, "tags": ["IoT", "Leak", "Smart Home", "Water"], "source": "Indie Hacker 2025"},
        {"title": "Smart Inventory Shelf", "description": "Weight-sensing smart shelves with real-time inventory tracking, low-stock alerts, and automated reordering.", "problem_statement": "Retailers lose sales from out-of-stock items and waste from overstock.", "solution": "IoT smart shelves that track inventory in real-time and automate reordering.", "key_features": ["Weight sensing", "Real-time stock", "Low-stock alerts", "Auto reordering", "Analytics"], "innovation_score": 78, "market_potential": 84, "complexity": "HARD", "sub_category": "Retail", "suggested_stack": {"hardware": "ESP32 + load cells", "backend": "Python FastAPI", "database": "PostgreSQL", "integrations": "ERP systems"}, "tags": ["IoT", "Retail", "Inventory", "Smart Shelf"], "source": "Hackathon Winner 2025"},
    ],
    "DESKTOP": [
        {"title": "Offline-first Note-taking App", "description": "Lightning-fast, offline-first note-taking with markdown support, local-first sync, and keyboard shortcut everything.", "problem_statement": "Cloud note apps are slow, require internet, and have privacy concerns.", "solution": "Local-first notes app with instant open, offline support, and encrypted sync as option.", "key_features": ["Offline first", "Markdown", "Keyboard shortcuts", "Local search", "Encrypted sync"], "innovation_score": 70, "market_potential": 80, "complexity": "EASY", "sub_category": "Productivity", "suggested_stack": {"frontend": "Electron + React", "database": "SQLite (local)", "sync": "Optional CRDT"}, "tags": ["Desktop", "Notes", "Productivity", "Offline"], "source": "GitHub Trending 2025"},
        {"title": "Developer Time Tracker", "description": "Automatic time tracking for developers that logs projects, branches, and tools used — no manual entry.", "problem_statement": "Developers hate manual time tracking and existing tools interrupt workflow.", "solution": "Background time tracker that automatically logs coding activity by project and tool.", "key_features": ["Auto-detection", "Project tracking", "Tool logging", "Reports", "Integrations"], "innovation_score": 74, "market_potential": 72, "complexity": "EASY", "sub_category": "DevTools", "suggested_stack": {"frontend": "Tauri + React", "backend": "Rust", "database": "SQLite"}, "tags": ["Desktop", "Time Tracking", "DevTools", "Productivity"], "source": "Product Hunt 2025"},
        {"title": "Local AI Image Editor", "description": "AI-powered image editor that runs entirely locally — no cloud dependency, no subscription, full privacy.", "problem_statement": "AI image tools require cloud subscriptions and upload sensitive images to servers.", "solution": "Desktop app with local AI models for image editing — fully private and offline.", "key_features": ["Local AI models", "Image editing", "Privacy-first", "No subscription", "Batch processing"], "innovation_score": 88, "market_potential": 76, "complexity": "HARD", "sub_category": "Creativity", "suggested_stack": {"frontend": "Electron + React", "ai": "Stable Diffusion (ONNX)", "backend": "Python", "database": "SQLite"}, "tags": ["Desktop", "AI", "Image Editing", "Privacy"], "source": "Hackathon Winner 2025"},
        {"title": "System Resource Monitor Pro", "description": "Beautiful, customizable system monitor with historical graphs, alerting, and process management.", "problem_statement": "Task Manager and Activity Monitor lack historical data and customization.", "solution": "Desktop system monitor with rich graphs, custom alerts, and process insights.", "key_features": ["CPU/GPU/RAM graphs", "Custom alerts", "Process management", "Historical data", "Themes"], "innovation_score": 66, "market_potential": 64, "complexity": "MEDIUM", "sub_category": "Utilities", "suggested_stack": {"frontend": "Tauri + React", "backend": "Rust", "database": "SQLite"}, "tags": ["Desktop", "System", "Monitor", "Utilities"], "source": "GitHub Trending 2025"},
        {"title": "Cross-Platform Clipboard Manager", "description": "Universal clipboard history with sync across devices, rich snippets, and smart paste suggestions.", "problem_statement": "System clipboard only holds one item and loses history on restart.", "solution": "Clipboard manager with history, sync, snippets, and smart paste.", "key_features": ["Clipboard history", "Cross-device sync", "Snippets", "Search", "Smart paste"], "innovation_score": 68, "market_potential": 74, "complexity": "MEDIUM", "sub_category": "Productivity", "suggested_stack": {"frontend": "Electron + React", "backend": "Rust", "sync": "End-to-end encrypted"}, "tags": ["Desktop", "Clipboard", "Productivity", "Sync"], "source": "Product Hunt 2025"},
        {"title": "Music Production DAW Lite", "description": "Free, open-source DAW for beginners with AI-powered mixing suggestions and built-in sample library.", "problem_statement": "Professional DAWs are expensive and complex for beginners learning music production.", "solution": "Free, beginner-friendly DAW with AI assistance and curated sample library.", "key_features": ["Multi-track", "AI mixing", "Sample library", "MIDI support", "Export"], "innovation_score": 80, "market_potential": 72, "complexity": "HARD", "sub_category": "Creativity", "suggested_stack": {"frontend": "JUCE + React", "backend": "C++", "ai": "TensorFlow", "database": "SQLite"}, "tags": ["Desktop", "Music", "DAW", "AI", "Open Source"], "source": "GitHub Trending 2025"},
        {"title": "Screen OCR Tool", "description": "Select any area of screen to extract text using OCR — works offline, supports 100+ languages.", "problem_statement": "Users need to extract text from images, videos, and locked PDFs frequently.", "solution": "Quick screen OCR tool with language detection and formatting preservation.", "key_features": ["Screen capture", "OCR extraction", "100+ languages", "Formatting", "Copy/paste"], "innovation_score": 64, "market_potential": 70, "complexity": "EASY", "sub_category": "Utilities", "suggested_stack": {"frontend": "Tauri + React", "backend": "Rust + Tesseract"}, "tags": ["Desktop", "OCR", "Screen Capture", "Utilities"], "source": "Indie Hacker 2025"},
        {"title": "Personal Finance Manager", "description": "Desktop finance app with bank sync, budgeting, investment tracking, and financial goal planning.", "problem_statement": "Personal finance tools are either too simple (apps) or too complex (Excel).", "solution": "Desktop finance manager balancing simplicity with powerful features.", "key_features": ["Bank sync", "Budgeting", "Investment tracking", "Goal planning", "Reports"], "innovation_score": 72, "market_potential": 78, "complexity": "MEDIUM", "sub_category": "Finance", "suggested_stack": {"frontend": "Electron + React", "backend": "Node.js", "database": "SQLite + encryption"}, "tags": ["Desktop", "Finance", "Budget", "Investment"], "source": "YC Startup 2024"},
        {"title": "E-book Reader & Manager", "description": "Feature-rich e-book reader with format conversion, library management, annotation, and sync.", "problem_statement": "E-book management is fragmented across devices and formats.", "solution": "Universal e-book reader with format support, library management, and cross-device sync.", "key_features": ["Multiple formats", "Library management", "Annotations", "Sync", "Conversion"], "innovation_score": 68, "market_potential": 66, "complexity": "MEDIUM", "sub_category": "Lifestyle", "suggested_stack": {"frontend": "Electron + React", "backend": "Node.js", "database": "SQLite"}, "tags": ["Desktop", "E-books", "Reading", "Library"], "source": "GitHub Trending 2025"},
        {"title": "Video Downloader Manager", "description": "Download videos from any platform, convert formats, schedule downloads, and organize library.", "problem_statement": "Video streaming doesn't work offline and existing download tools are limited.", "solution": "Universal video downloader supporting multiple platforms with format conversion.", "key_features": ["Multi-platform", "Format conversion", "Schedule", "Library", "Playlist support"], "innovation_score": 60, "market_potential": 72, "complexity": "MEDIUM", "sub_category": "Utilities", "suggested_stack": {"frontend": "Electron + React", "backend": "Python (yt-dlp)", "database": "SQLite"}, "tags": ["Desktop", "Video", "Downloader", "Utilities"], "source": "GitHub Trending 2025"},
    ],
    "EXTENSION": [
        {"title": "AI Writing Assistant for Chrome", "description": "Chrome extension that improves writing across all text fields — grammar, tone, clarity, and style suggestions.", "problem_statement": "People write poorly in emails, forms, and social media — grammar tools feel robotic.", "solution": "Context-aware writing assistant that adapts suggestions to each platform's tone.", "key_features": ["Grammar check", "Tone adjustment", "Platform-aware", "Quick rewrite", "Style guide"], "innovation_score": 76, "market_potential": 90, "complexity": "MEDIUM", "sub_category": "Writing", "suggested_stack": {"frontend": "Chrome Extension API", "ai": "OpenAI API", "backend": "None (client-side AI)"}, "tags": ["Extension", "AI", "Writing", "Productivity"], "source": "Product Hunt 2025"},
        {"title": "Tab Manager & Suspender", "description": "Intelligent tab manager that auto-suspends inactive tabs, groups by project, and saves sessions.", "problem_statement": "Browser tabs consume memory and create visual clutter — power users have 50+ open.", "solution": "Smart tab manager with auto-suspend, grouping, and session management.", "key_features": ["Auto-suspend", "Tab groups", "Session save", "Memory stats", "Search"], "innovation_score": 68, "market_potential": 82, "complexity": "EASY", "sub_category": "Productivity", "suggested_stack": {"frontend": "Chrome Extension API", "storage": "chrome.storage.local"}, "tags": ["Extension", "Tabs", "Productivity", "Memory"], "source": "GitHub Trending 2025"},
        {"title": "Price History Tracker", "description": "Shows price history chart and sets price drop alerts on any e-commerce product page.", "problem_statement": "E-commerce prices fluctuate daily — shoppers don't know if they're getting a good deal.", "solution": "Extension showing price history and notifying on drops for any product.", "key_features": ["Price history", "Drop alerts", "Comparison", "Wish list", "Data export"], "innovation_score": 70, "market_potential": 84, "complexity": "EASY", "sub_category": "Shopping", "suggested_stack": {"frontend": "Chrome Extension API + Chart.js", "backend": "Python (scraper)", "database": "PostgreSQL"}, "tags": ["Extension", "Shopping", "Price", "Tracking"], "source": "Product Hunt 2025"},
        {"title": "Website Color Analyzer", "description": "Instantly extracts color palette, typography, and design tokens from any website for designers.", "problem_statement": "Designers manually inspect websites to understand their design system.", "solution": "One-click design token extraction from any website.", "key_features": ["Color extraction", "Typography detection", "Design tokens", "Copy palette", "Export"], "innovation_score": 72, "market_potential": 68, "complexity": "EASY", "sub_category": "Design", "suggested_stack": {"frontend": "Chrome Extension API", "parsing": "CSS parser"}, "tags": ["Extension", "Design", "Colors", "DevTools"], "source": "Hackathon Winner 2025"},
        {"title": "LinkedIn Profile Enhancer", "description": "Suggests improvements to LinkedIn profiles — headline, summary, skills, and experience sections.", "problem_statement": "Professionals don't optimize LinkedIn profiles for recruiters and algorithms.", "solution": "AI extension that analyzes and suggests LinkedIn profile improvements.", "key_features": ["Profile analysis", "Section suggestions", "Keyword optimization", "Score", "Preview"], "innovation_score": 74, "market_potential": 78, "complexity": "MEDIUM", "sub_category": "Career", "suggested_stack": {"frontend": "Chrome Extension API", "ai": "OpenAI API", "backend": "Node.js"}, "tags": ["Extension", "LinkedIn", "Career", "AI"], "source": "YC Startup 2025"},
        {"title": "Focus Mode Blocker", "description": "Distraction blocker with smart detection — blocks sites based on context, time of day, and work patterns.", "problem_statement": "Existing site blockers are too simple — block all or nothing with no context awareness.", "solution": "Context-aware focus assistant that adapts blocking rules to work patterns.", "key_features": ["Smart blocking", "Context detection", "Schedule", "Stats", "Whitelist/blacklist"], "innovation_score": 66, "market_potential": 74, "complexity": "EASY", "sub_category": "Productivity", "suggested_stack": {"frontend": "Chrome Extension API", "storage": "chrome.storage.sync"}, "tags": ["Extension", "Focus", "Productivity", "Blocking"], "source": "GitHub Trending 2025"},
        {"title": "GitHub PR Reviewer", "description": "Adds code review enhancements to GitHub — inline comments, custom checks, and review templates.", "problem_statement": "GitHub's native PR review interface lacks templates and custom automation.", "solution": "Extension that enhances GitHub PR reviews with templates and automation.", "key_features": ["Review templates", "Custom checks", "Inline comments", "Approval workflows", "Stats"], "innovation_score": 70, "market_potential": 72, "complexity": "MEDIUM", "sub_category": "DevTools", "suggested_stack": {"frontend": "Chrome Extension API", "backend": "GitHub API"}, "tags": ["Extension", "GitHub", "Code Review", "DevTools"], "source": "Hackathon Winner 2025"},
        {"title": "Translation Overlay", "description": "Hover over any text to get instant translation in 100+ languages with pronunciation.", "problem_statement": "Reading foreign language content requires switching tabs to translation tools.", "solution": "Hover-to-translate extension with instant results and pronunciation.", "key_features": ["Hover translate", "100+ languages", "Pronunciation", "Auto-detect", "Settings"], "innovation_score": 64, "market_potential": 80, "complexity": "EASY", "sub_category": "Utilities", "suggested_stack": {"frontend": "Chrome Extension API", "api": "Translation API"}, "tags": ["Extension", "Translation", "Languages", "Utilities"], "source": "Product Hunt 2025"},
        {"title": "Email Tracking Blocker", "description": "Blocks email open tracking pixels and read receipts in Gmail/Outlook web clients.", "problem_statement": "Email senders can track when and where you open emails without consent.", "solution": "Extension that blocks tracking pixels and notifies users when blocked.", "key_features": ["Tracker blocking", "Notification", "Privacy stats", "Whitelist", "No data collection"], "innovation_score": 72, "market_potential": 68, "complexity": "EASY", "sub_category": "Privacy", "suggested_stack": {"frontend": "Chrome Extension API"}, "tags": ["Extension", "Privacy", "Email", "Tracking"], "source": "GitHub Trending 2025"},
        {"title": "Form Auto-Filler", "description": "Intelligent form filler that learns from past entries and auto-fills repeating form fields.", "problem_statement": "Filling repetitive online forms wastes hours weekly for many professionals.", "solution": "Smart form auto-filler that learns patterns and fills fields accurately.", "key_features": ["Pattern learning", "Auto-fill", "Multi-profile", "Field detection", "Encrypted storage"], "innovation_score": 68, "market_potential": 76, "complexity": "MEDIUM", "sub_category": "Productivity", "suggested_stack": {"frontend": "Chrome Extension API", "storage": "chrome.storage.local + encryption"}, "tags": ["Extension", "Forms", "Auto-fill", "Productivity"], "source": "Indie Hacker 2025"},
    ],
    "API_BACKEND": [
        {"title": "Unified Payment Gateway API", "description": "Single API integrating Stripe, PayPal, Razorpay, and other payment providers with automatic failover.", "problem_statement": "Businesses need multiple payment providers but each has different API and compliance requirements.", "solution": "Unified payment API with one integration that routes to multiple processors.", "key_features": ["Multi-provider", "Auto failover", "Smart routing", "Reconciliation", "Webhook management"], "innovation_score": 80, "market_potential": 95, "complexity": "HARD", "sub_category": "FinTech", "suggested_stack": {"backend": "Python FastAPI", "database": "PostgreSQL", "integrations": "Stripe/PayPal/Razorpay APIs"}, "tags": ["API", "Payments", "FinTech", "Integration"], "source": "YC Startup 2025"},
        {"title": "SMS/Email Notification Service", "description": "White-label notification infrastructure with templates, scheduling, delivery tracking, and multi-channel support.", "problem_statement": "Building reliable notification infrastructure requires significant engineering effort.", "solution": "API-first notification service with templates, scheduling, and delivery analytics.", "key_features": ["Multi-channel", "Template engine", "Scheduling", "Delivery tracking", "Analytics"], "innovation_score": 68, "market_potential": 82, "complexity": "MEDIUM", "sub_category": "Infrastructure", "suggested_stack": {"backend": "Go", "database": "PostgreSQL + Redis", "infra": "Kubernetes"}, "tags": ["API", "Notifications", "Infrastructure", "SMS", "Email"], "source": "Product Hunt 2025"},
        {"title": "Data Sync API (Postgres → BI)", "description": "Real-time data synchronization from PostgreSQL to BI tools (Tableau, Metabase, PowerBI) with schema mapping.", "problem_statement": "Data teams write custom ETL pipelines to sync databases to BI tools.", "solution": "Managed sync service that connects PostgreSQL to BI tools with live schema mapping.", "key_features": ["Real-time sync", "Schema mapping", "Multi-destination", "Transformation", "Monitoring"], "innovation_score": 74, "market_potential": 76, "complexity": "HARD", "sub_category": "Data", "suggested_stack": {"backend": "Rust", "database": "PostgreSQL", "infra": "Kafka + Debezium"}, "tags": ["API", "Data", "ETL", "BI", "Sync"], "source": "GitHub Trending 2025"},
        {"title": "API Key Management Service", "description": "Managed API key service with rate limiting, usage analytics, key rotation, and developer portal.", "problem_statement": "Every SaaS needs API key management but building it in-house is boilerplate-heavy.", "solution": "Drop-in API key infrastructure with dashboard, rate limiting, and analytics.", "key_features": ["Key generation", "Rate limiting", "Usage analytics", "Key rotation", "Developer portal"], "innovation_score": 70, "market_potential": 78, "complexity": "MEDIUM", "sub_category": "Infrastructure", "suggested_stack": {"backend": "Python FastAPI", "database": "PostgreSQL + Redis"}, "tags": ["API", "Keys", "Infrastructure", "Security"], "source": "Hackathon Winner 2025"},
        {"title": "Webhook Receiver & Forwarder", "description": "Reliable webhook infrastructure with retry logic, logging, filtering, and delivery guarantees.", "problem_statement": "Building reliable webhook processing is surprisingly complex — lost webhooks are common.", "solution": "Webhook infrastructure service with guaranteed delivery and debugging tools.", "key_features": ["Webhook reception", "Filtering", "Retry logic", "Log viewer", "Testing tools"], "innovation_score": 66, "market_potential": 74, "complexity": "MEDIUM", "sub_category": "Infrastructure", "suggested_stack": {"backend": "Node.js", "database": "PostgreSQL", "queue": "Redis/Bull"}, "tags": ["API", "Webhooks", "Infrastructure", "Events"], "source": "GitHub Trending 2025"},
        {"title": "Content Moderation API", "description": "AI-based content moderation for text, images, and videos with customizable policies and real-time scoring.", "problem_statement": "User-generated content platforms need moderation but building it is complex and expensive.", "solution": "API for automated content moderation with customizable policy rules.", "key_features": ["Text moderation", "Image analysis", "Video screening", "Custom policies", "Real-time scoring"], "innovation_score": 78, "market_potential": 84, "complexity": "HARD", "sub_category": "Safety", "suggested_stack": {"backend": "Python FastAPI", "ai": "GPT-4 + CLIP", "database": "PostgreSQL"}, "tags": ["API", "Moderation", "AI", "Safety", "Content"], "source": "YC Startup 2025"},
        {"title": "GeoIP & Location API", "description": "Fast, accurate IP geolocation API with vpn/proxy detection, timezone, currency, and language data.", "problem_statement": "Businesses need location data for personalization, compliance, and security.", "solution": "High-accuracy IP geolocation API with proxy detection and enrichment data.", "key_features": ["IP lookup", "Geo coordinates", "VPN detection", "Timezone/currency", "Batch processing"], "innovation_score": 62, "market_potential": 76, "complexity": "EASY", "sub_category": "Infrastructure", "suggested_stack": {"backend": "Rust", "database": "PostgreSQL + IP data"}, "tags": ["API", "GeoIP", "Location", "Infrastructure"], "source": "Product Hunt 2025"},
        {"title": "PDF Generation API", "description": "Convert HTML/markdown to PDF with custom templates, headers/footers, and batch processing.", "problem_statement": "Generating PDFs from web content or templates requires complex tooling.", "solution": "Simple API to convert HTML to PDF with custom styling and templates.", "key_features": ["HTML to PDF", "Templates", "Watermark", "Batch", "Webhook callback"], "innovation_score": 60, "market_potential": 78, "complexity": "EASY", "sub_category": "Utilities", "suggested_stack": {"backend": "Node.js + Puppeteer", "database": "PostgreSQL", "storage": "S3"}, "tags": ["API", "PDF", "Documents", "Utilities"], "source": "GitHub Trending 2025"},
        {"title": "Scheduled Job & Cron API", "description": "Managed cron job service with HTTP endpoints, retries, logging, and monitoring.", "problem_statement": "Running cron jobs requires servers, maintenance, and monitoring infrastructure.", "solution": "Serverless cron API that triggers HTTP endpoints on schedule with full observability.", "key_features": ["Schedule management", "HTTP triggers", "Retry logic", "Execution logs", "Monitoring"], "innovation_score": 64, "market_potential": 72, "complexity": "EASY", "sub_category": "Infrastructure", "suggested_stack": {"backend": "Go", "database": "PostgreSQL", "scheduler": "Redis + distributed locks"}, "tags": ["API", "Cron", "Jobs", "Scheduling", "Infrastructure"], "source": "Hackathon Winner 2025"},
        {"title": "File Conversion API", "description": "Convert between 100+ file formats — documents, images, audio, video — with quality control.", "problem_statement": "File format conversion requires different tools for each format type.", "solution": "Unified file conversion API supporting all major formats with quality options.", "key_features": ["100+ formats", "Quality control", "Batch processing", "Webhook callback", "Storage integration"], "innovation_score": 58, "market_potential": 74, "complexity": "MEDIUM", "sub_category": "Utilities", "suggested_stack": {"backend": "Python + FFmpeg/LibreOffice", "queue": "Redis/Bull", "storage": "S3"}, "tags": ["API", "Conversion", "Files", "Utilities"], "source": "Product Hunt 2025"},
    ],
}

def seed():
    db = SessionLocal()
    existing = db.query(CuratedIdea).count()
    if existing > 0:
        print(f"Database already has {existing} curated ideas. Skipping seed.")
        return

    count = 0
    for platform, ideas in CURATED_IDEAS.items():
        for idea_data in ideas:
            idea = CuratedIdea(
                title=idea_data["title"],
                description=idea_data["description"],
                problem_statement=idea_data["problem_statement"],
                solution=idea_data["solution"],
                key_features=idea_data["key_features"],
                platform=platform,
                sub_category=idea_data.get("sub_category", "General"),
                innovation_score=idea_data["innovation_score"],
                market_potential=idea_data["market_potential"],
                complexity=idea_data["complexity"],
                suggested_stack=idea_data.get("suggested_stack"),
                tags=idea_data.get("tags", []),
                source=idea_data.get("source", "Curated"),
                trending_score=idea_data.get("innovation_score", 50),
            )
            db.add(idea)
            count += 1
    db.commit()
    db.close()
    print(f"Successfully seeded {count} curated ideas across {len(CURATED_IDEAS)} platforms.")

if __name__ == "__main__":
    seed()
