"use client";

import React, { useState } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { archaeologyApi } from "@/lib/api";
import type { ArchaeologyReport } from "@/lib/types";
import {
  Code2,
  GitBranch,
  Globe,
  Loader2,
  ChevronRight,
  CheckCircle2,
  Download,
  Lightbulb,
  TrendingUp,
  Target,
  BarChart3,
  AlertTriangle,
  Server,
  Layers,
} from "lucide-react";

interface ArcheologyResultWithStack extends ArchaeologyReport {
  detected_stack?: Record<string, string[]>;
  architecture_grade?: string;
}

const tabs = [
  { id: "paste", label: "Paste Code", icon: Code2 },
  { id: "github", label: "GitHub URL", icon: GitBranch },
  { id: "website", label: "Website URL", icon: Globe },
];

const gradeColors: Record<string, string> = {
  A: "text-green-600 bg-green-50 border-green-200",
  B: "text-blue-600 bg-blue-50 border-blue-200",
  C: "text-yellow-600 bg-yellow-50 border-yellow-200",
  D: "text-orange-600 bg-orange-50 border-orange-200",
  F: "text-red-600 bg-red-50 border-red-200",
};

export default function AnalyzePage() {
  const [tab, setTab] = useState("paste");
  const [code, setCode] = useState("");
  const [url, setUrl] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [report, setReport] = useState<ArcheologyResultWithStack | null>(null);
  const [expandedSections, setExpandedSections] = useState<string[]>(["analysis"]);

  const toggleSection = (id: string) => {
    setExpandedSections((prev) =>
      prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
    );
  };

  const handleExportPDF = async () => {
    if (!report) return;
    const markdown = [
      "# Archaeology Report",
      "",
      "## Code Analysis",
      report.codeAnalysis,
      "",
      "## Design Patterns",
      report.patterns,
      "",
      "## Evolution Timeline",
      report.evolutionTimeline,
      "",
      "## Developer Psychology",
      report.developerPsychology,
      "",
      "## Scores",
      `- Originality: ${report.scores.originality}/100`,
      `- Feasibility: ${report.scores.feasibility}/100`,
      `- Market Potential: ${report.scores.market}/100`,
      `- Complexity: ${report.scores.complexity}/100`,
      "",
      "## Future Versions",
      ...report.futureVersions.map((v) => `- ${v}`),
      "",
      "---",
      "*Generated by IdeaDNA — Code Archaeology Engine*",
    ].join("\n");

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `archaeology-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleAnalyze = async (e: React.FormEvent) => {
    e.preventDefault();
    if (tab === "paste" && !code.trim()) return;
    if (tab !== "paste" && !url.trim()) return;
    setIsAnalyzing(true);
    setReport(null);
    setError(null);

    try {
      let result;
      if (tab === "paste") {
        result = await archaeologyApi.analyzeCode(code);
      } else if (tab === "github") {
        result = await archaeologyApi.analyzeGithub(url);
      } else {
        result = await archaeologyApi.analyzeWebsite(url);
      }

      const data = result.data;
      setReport({
        codeAnalysis: data.code_analysis,
        patterns: data.patterns,
        evolutionTimeline: data.evolution_timeline,
        developerPsychology: data.developer_psychology,
        scores: {
          originality: data.scores.originality ?? data.scores.originality,
          feasibility: data.scores.feasibility ?? data.scores.feasibility,
          market: data.scores.market_potential ?? data.scores.market,
          complexity: data.scores.complexity ?? data.scores.complexity,
        },
        futureVersions: data.future_versions ?? [],
        detected_stack: data.detected_stack,
        architecture_grade: data.architecture_grade,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Analysis failed");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const sections = report
    ? [
        { id: "analysis", label: "Code Analysis", content: report.codeAnalysis, icon: Code2 },
        { id: "patterns", label: "Design Patterns", content: report.patterns, icon: Lightbulb },
        { id: "timeline", label: "Evolution Timeline", content: report.evolutionTimeline, icon: TrendingUp },
        { id: "psychology", label: "Developer Psychology", content: report.developerPsychology, icon: Target },
      ]
    : [];

  return (
    <DashboardLayout>
      <div className="p-6 max-w-6xl">
        <div className="mb-6">
          <div className="flex items-center gap-1.5 mb-1">
            <Code2 className="w-4 h-4 text-notionBlue" />
            <span className="text-xs font-bold uppercase tracking-wider text-notionGray">Code Archaeology</span>
          </div>
          <h1 className="text-xl font-bold tracking-tight">Analyze Code</h1>
          <p className="text-xs text-notionGray mt-0.5">Reverse-engineer developer thinking from any codebase</p>
        </div>

        <form onSubmit={handleAnalyze} className="bg-white border border-notionBorder rounded-xl notion-shadow overflow-hidden mb-6 max-w-2xl">
          <div className="flex border-b border-notionBorder">
            {tabs.map((t) => (
              <button key={t.id} type="button" onClick={() => setTab(t.id)} className={`flex items-center gap-1.5 px-4 py-2.5 text-xs font-medium transition-colors ${
                tab === t.id ? "text-notionBlue border-b-2 border-notionBlue bg-notionBlue/5" : "text-notionGray hover:text-black"
              }`}>
                <t.icon className="w-3.5 h-3.5" /> {t.label}
              </button>
            ))}
          </div>

          <div className="p-4">
            {tab === "paste" && (
              <textarea
                placeholder="Paste your code here..."
                value={code}
                onChange={(e) => setCode(e.target.value)}
                rows={10}
                className="w-full px-3 py-2 text-xs font-mono border border-notionBorder rounded-[4px] outline-none focus:border-notionBlue resize-none bg-[#fafafa]"
              />
            )}
            {tab === "github" && (
              <input type="url" placeholder="https://github.com/username/repository" value={url} onChange={(e) => setUrl(e.target.value)} className="w-full px-3 py-2 text-sm border border-notionBorder rounded-[4px] outline-none focus:border-notionBlue" />
            )}
            {tab === "website" && (
              <div>
                <input type="url" placeholder="https://example.com" value={url} onChange={(e) => setUrl(e.target.value)} className="w-full px-3 py-2 text-sm border border-notionBorder rounded-[4px] outline-none focus:border-notionBlue" />
                <p className="text-[10px] text-notionGray mt-1.5">Only public websites. Ensure you have permission to analyze.</p>
              </div>
            )}

            <div className="mt-4">
              <Button type="submit" disabled={isAnalyzing || (tab === "paste" ? !code.trim() : !url.trim())}>
                {isAnalyzing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Code2 className="w-4 h-4" />}
                {isAnalyzing ? "Excavating code..." : "Analyze"}
              </Button>
            </div>
          </div>
        </form>

        {error && (
          <div className="mb-6 bg-red-50 border border-red-200 rounded-xl p-4 max-w-2xl">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-red-500" />
              <span className="text-xs font-semibold text-red-700">{error}</span>
            </div>
          </div>
        )}

        {isAnalyzing && (
          <div className="flex flex-col items-center justify-center py-16">
            <Loader2 className="w-8 h-8 text-notionBlue animate-spin mb-3" />
            <p className="text-sm font-semibold">CodeArchaeologist running...</p>
            <div className="flex gap-2 mt-3">
              {["Parsing", "Patterns", "History", "Psychology", "Scoring", "Report"].map((s, i) => (
                <div key={s} className="flex items-center gap-1">
                  <div className={`w-2 h-2 rounded-full ${i <= 2 ? "bg-notionBlue" : "bg-notionBorder"}`} />
                  <span className={`text-[9px] font-mono ${i <= 2 ? "text-notionBlue" : "text-notionGray"}`}>{s}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {report && !isAnalyzing && (
          <div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <h2 className="text-sm font-bold tracking-tight">Archaeology Report</h2>
                <Badge variant="sky">
                  {report.architecture_grade ? `Grade ${report.architecture_grade}` : "Complete"}
                </Badge>
              </div>
              <div className="flex gap-2">
                <Button variant="secondary" size="sm" onClick={handleExportPDF}>
                  <Download className="w-3 h-3" /> Export MD
                </Button>
              </div>
            </div>

            {/* Stack & Grade */}
            {report.detected_stack && Object.keys(report.detected_stack).length > 0 && (
              <div className="bg-white border border-notionBorder rounded-xl notion-shadow p-4 mb-4">
                <div className="flex items-center gap-2 mb-3">
                  <Layers className="w-4 h-4 text-notionBlue" />
                  <h3 className="text-xs font-semibold uppercase tracking-wider text-notionGray">Detected Stack</h3>
                </div>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
                  {Object.entries(report.detected_stack).map(([key, values]) => (
                    <div key={key}>
                      <span className="font-semibold text-notionGray block mb-1 capitalize">{key}</span>
                      <div className="flex flex-wrap gap-1">
                        {(values as string[]).map((v) => (
                          <span key={v} className="bg-[#f6f5f4] px-2 py-0.5 rounded-full text-[10px] font-mono">{v}</span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
                {report.architecture_grade && (
                  <div className="mt-3 pt-3 border-t border-notionBorder flex items-center gap-2">
                    <Server className="w-3.5 h-3.5 text-notionGray" />
                    <span className="text-[10px] text-notionGray">Architecture Grade:</span>
                    <span className={`text-xs font-bold px-2 py-0.5 rounded border ${gradeColors[report.architecture_grade] || gradeColors.B}`}>
                      {report.architecture_grade}
                    </span>
                  </div>
                )}
              </div>
            )}

            {/* Score Cards */}
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-4 mb-6">
              {[
                { label: "Originality", value: report.scores.originality, color: "text-stickerPurple" },
                { label: "Feasibility", value: report.scores.feasibility, color: "text-stickerTeal" },
                { label: "Market Potential", value: report.scores.market, color: "text-stickerSky" },
                { label: "Complexity", value: report.scores.complexity, color: "text-notionBlue" },
              ].map((s) => (
                <div key={s.label} className="bg-white border border-notionBorder rounded-xl notion-shadow p-4">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-[11px] text-notionGray font-medium">{s.label}</span>
                    <BarChart3 className={`w-3.5 h-3.5 ${s.color}`} />
                  </div>
                  <span className={`text-xl font-bold ${s.color}`}>{s.value}</span>
                  <span className="text-[10px] text-notionGray ml-1">/100</span>
                </div>
              ))}
            </div>

            {/* Sections */}
            <div className="bg-white border border-notionBorder rounded-xl notion-shadow overflow-hidden mb-6">
              {sections.map((sec) => {
                const expanded = expandedSections.includes(sec.id);
                return (
                  <div key={sec.id} className="border-b border-notionBorder last:border-b-0">
                    <button onClick={() => toggleSection(sec.id)} className="w-full flex items-center justify-between px-4 py-3 hover:bg-[#f6f5f4] transition-colors">
                      <div className="flex items-center gap-2">
                        <sec.icon className="w-4 h-4 text-notionBlue" />
                        <span className="text-sm font-semibold">{sec.label}</span>
                      </div>
                      <ChevronRight className={`w-4 h-4 text-notionGray transition-transform ${expanded ? "rotate-90" : ""}`} />
                    </button>
                    {expanded && <div className="px-4 pb-4 text-xs text-notionGray leading-relaxed whitespace-pre-line">{sec.content}</div>}
                  </div>
                );
              })}
            </div>

            {/* Future Versions */}
            {report.futureVersions.length > 0 && (
              <div className="bg-white border border-notionBorder rounded-xl notion-shadow p-4">
                <h3 className="text-xs font-semibold uppercase tracking-wider text-notionGray mb-3">Suggested Future Versions</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {report.futureVersions.map((v, i) => (
                    <div key={i} className="flex items-start gap-2 p-2.5 rounded-[8px] border border-notionBorder hover:border-black/30 transition-colors">
                      <CheckCircle2 className="w-4 h-4 text-stickerTeal mt-0.5 shrink-0" />
                      <span className="text-xs">{v}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {!report && !isAnalyzing && !error && (
          <div className="text-center py-16">
            <Code2 className="w-10 h-10 text-notionGray/30 mx-auto mb-3" />
            <p className="text-sm text-notionGray">Paste code or enter a URL to analyze</p>
            <p className="text-xs text-notionGray mt-1">Our CodeArchaeologist will reverse-engineer the architecture</p>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
