import json
from sqlalchemy.orm import Session
from app.models.idea import Blueprint, UiMockup


class ExportService:

    def export_blueprint_markdown(self, db: Session, idea_id: int) -> str | None:
        bp = db.query(Blueprint).filter(Blueprint.idea_id == idea_id).first()
        if not bp:
            return None

        lines = [
            f"# {bp.overview or 'Blueprint'}",
            "",
            "## Overview",
            bp.overview or "N/A",
            "",
            "## PRD",
            self._dict_to_md(bp.prd),
            "",
            "## Tech Stack",
            self._dict_to_md(bp.tech_stack),
            "",
            "## Database Schema",
            self._dict_to_md(bp.database_schema),
            "",
            "## API Design",
            self._dict_to_md(bp.api_design),
            "",
            "## User Flow",
            self._list_to_md(bp.user_flow),
            "",
            "## Implementation Plan",
            self._dict_to_md(bp.implementation_plan),
            "",
            "---",
            f"*Generated by IdeaDNA v2.0 — {bp.created_at.strftime('%Y-%m-%d %H:%M')}*" if bp.created_at else "",
        ]
        return "\n".join(lines)

    def export_blueprint_json(self, db: Session, idea_id: int) -> dict | None:
        bp = db.query(Blueprint).filter(Blueprint.idea_id == idea_id).first()
        if not bp:
            return None
        return {
            "overview": bp.overview,
            "prd": bp.prd,
            "tech_stack": bp.tech_stack,
            "database_schema": bp.database_schema,
            "api_design": bp.api_design,
            "user_flow": bp.user_flow,
            "implementation_plan": bp.implementation_plan,
            "generated_at": bp.created_at.isoformat() if bp.created_at else None,
        }

    def export_mockup_html(self, db: Session, idea_id: int) -> str | None:
        mu = db.query(UiMockup).filter(UiMockup.idea_id == idea_id).first()
        if not mu:
            return None
        return mu.html

    def _dict_to_md(self, d) -> str:
        if not d:
            return "N/A"
        if isinstance(d, dict):
            return "\n".join(f"- **{k}**: {v}" for k, v in d.items())
        return str(d)

    def _list_to_md(self, items) -> str:
        if not items:
            return "N/A"
        if isinstance(items, list):
            return "\n".join(f"- {item}" for item in items)
        return str(items)
